name: Deploy to IWSKlanten

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to IWSKlanten
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: touch /home/deb50767n5/test
          host: ${{ secrets.HOST }}
          username: deb50767n5
          password: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
        env:
          CI: true
